package savagerifts.model.benefittable;

public enum BenefitTableType {
	BODY_ARMOR, 
	CLOSE_COMBAT_WEAPONS,
	CYBERNETICS,
	EDUCATION, 
	ENCHANTED_ITEMS_MYSTIC_GADGETS, 
	EXPERIENCE_WISDOM,
	MAGIC_MYSTICISM, 
	PSIONICS, 
	RANGED_WEAPONS, 
	TRAINING, 
	UNDERWORLD_BLACK_OPS;
}