package savagerifts.model.race;

public enum RaceAbilityType {
	
	COMBAT_CYBORG_ABILITY_1,
	COMBAT_CYBORG_ABILITY_2,
	COMBAT_CYBORG_ABILITY_3,
	COMBAT_CYBORG_ABILITY_4,
	COMBAT_CYBORG_ABILITY_5,
	COMBAT_CYBORG_ABILITY_6,
	COMBAT_CYBORG_ABILITY_7,
	COMBAT_CYBORG_ABILITY_8,
	COMBAT_CYBORG_COMPLICATION_1,
	COMBAT_CYBORG_COMPLICATION_2,
	COMBAT_CYBORG_COMPLICATION_3,
	COMBAT_CYBORG_COMPLICATION_4,
	COMBAT_CYBORG_COMPLICATION_5,
	COMBAT_CYBORG_COMPLICATION_6,
	COMBAT_CYBORG_COMPLICATION_7,
	COMBAT_CYBORG_COMPLICATION_8,
	COMBAT_CYBORG_COMPLICATION_9,
	
	CRAZY_ABILITY_1,
	CRAZY_ABILITY_2,
	CRAZY_ABILITY_3,
	CRAZY_ABILITY_4,
	CRAZY_ABILITY_5,
	CRAZY_ABILITY_6,
	CRAZY_ABILITY_7,
	CRAZY_ABILITY_8,
	CRAZY_COMPLICATION_1,
	CRAZY_COMPLICATION_2,
	CRAZY_COMPLICATION_3,
	CRAZY_COMPLICATION_4,
	CRAZY_COMPLICATION_5,
	
}