package savagerifts.model.race;

public enum RaceType {
	ALTARA("The Blind Warrior Women of Altara (more commonly called the Warrior Women) are all clones. Most are created under labcontrolled conditions by the Splugorth, although it is possible for an Altara to induce herself into asexual reproduction and produce a clone. Such clones rapidly mature to adults with the memories and capabilities of the spawning Altara. Most Warrior Women are brainwashed, abjectly loyal servants of the Splugorth, yet there are those who break their conditioning and rebel, seeking a life outside of service to Atlantis. Altara are spawned blind, though they have extraordinary sensory abilities to overcome this. They are also genetically engineered to be superior physical specimens. Genetically and magically engineered for combat, Altara tend to be action oriented. They rarely speak and have a decidedly warrior-first view of everything. Rogues usually wear sunglasses, visors, goggles, or hoods to hide the utter lack of eyes on their face. They do this to avoid the prejudice of those who assume they are still serving the Slavers, as well as to avoid easy detection by those who would hunt them down for Atlantis."),
	D_NORR("Though not supernaturally connected to evil in any way, the D’Norr are more colloquially referred to as “Devilmen” due to their distinctive appearance. Otherwise looking similar to humans, their heads and faces give them the moniker. They have an elongated cranium dotted with tiny spines extending up and back from the forehead (dark red for males, purple for females), and two small horns above the brow. Their overall skin tone is tan-red, and the males have a series of tiny spines on their chins. All have dark blue eyes and pointed ears. D’Norr are known, by those willing to know them, as intelligent, compassionate, and drawn to nonviolent pursuits and social interaction. Many seek a pacifist’s path, at least as much as possible in such a dangerous world. Most seek out new experiences, new people, and new ideas. Due to their open nature and sensitivity, they are more susceptible to moments and sights of true horror but have a natural affinity for magic."),
	DOG_BOY("The Dog Boys’ existence is a testament to the ancient bond between canine and human. Exploiting that bond resulted in a soldier created to serve the Coalition in its war against the supernatural. The misuse of this relationship galls many, but they needn’t bother explaining to the typical Dog Boy; he won’t care, he’s just happy to serve! Most Dog Boys serve the Coalition States, either in the military or security forces. They don’t enjoy the same rights as humans, yet are generally treated well by those who command them. Most Coalition Grunts have only love and respect for the Dog Boys, who throw themselves fearlessly into any fray, prepared to die to protect their humans. Dog Boys encountered outside Coalition service are considered “feral” by the CS, to be put down on sight. They represent the isolated instances where constant abuse or an awakened conscience drove the being to reject the Coalition. An even fewer number are those born to two already-independent Dog Boys—the “free born.” Despite the name, not all Dog Boys are male. They are all humanoid even to the point of human-like hands and feet but retain a clearly canine head. Other factors such as size, coloration, and features depend heavily upon which breed of canine the Dog Boy is adapted from. The variety of Dog Boys is impressive, as the scientists responsible for creating them experimented extensively (and still do) to create specialized breeds for particular tasks and operational demands."),
	FENNODI("Called the “Quiet Walkers” by the Shoshone, the Fennodi are another race of generally peaceful D-Bees who prefer tending to herds of livestock on the prairies or similar outdoor pursuits. Pale gray and tan, with tiny black dots for eyes on the sides of their heads (embedded in small, mobile flaps that confuse others into thinking they are ears), the Fennodi have an effective 280-degree range of vision. Whisker-like fins on the sides of their jaws act as noses, giving them a wholly alien appearance to most humans. They’re very slender and tall, averaging seven feet in height. Fennodi are naturally psionic, with a set of powers indicative of their primarily peaceful nature (though they can certainly learn other powers). Most are encountered carrying the crescent Nymbu staff (a sacred traditional item representing travel and peace). Most Fennodi are practitioners of the Art of Nodox, a martial art focusing on avoidance and defense. Players of this D-Bee wanting to know the martial art should take Edges benefiting defense such as Martial Artist, Block, and Dodge."),
	GRACKLE_TOOTH("As monstrous as they appear, “The Mighty Grackles” tend to be some of the most easygoing D-Bees. Huge and beefy— averaging eight to 10 feet tall!—a Grackle Tooth has rawhide-like skin, ranging from tan to orange-rust in color, a saurian head full of teeth, tough spines on the shoulders and forearms, and powerful digigrade legs. He has four fingers and a thumb, but his legs end with two giant, clawed toes. Grackles also have surprisingly flexible prehensile tails. Grackles have no idea where they got the name (though most have a ready joke to make about the origin), nor where their species came from. They don’t care either, happy to call Earth home and willing to protect it. Most Grackles are up warriors, though a fair number enjoy mechanical and engineering pursuits. Grackles have no capacity for magic or psionics, and their biology makes cybernetic enhancements impossible."),
	LYN_SRIAL("Lyn-Srial are humanoids with four arms, bird-like heads, gleaming scales, and wings like a bat. Other races usually call them “Golden Ones” for their shining appearance or “Sky-Knights” due to their drive to help those in need. The Lyn-Srial are a serene people of artists, philosophers, and healers who would rather build communities than engage in combat, but who cannot abide evil. Lyn-Srial find spiritual magic appealing typically becoming Cloudweavers or Mystics (Cloudweavers use the M.A.R.S Personal Concept Option, taking AB (Miracles) and Master of Magic with trappings of air, wind, light, and the environment)."),
	PSI_STALKER("Psi-Stalkers are mutant humans who evolved from the chaos and catastrophes that plagued Rift Earth for centuries. Their tribes inhabit much of the wilds of North America, stalking magical and psionic beings for sustenance and the thrill of the hunt. They appear human except they average a bit taller (six to six-and-a-half feet), have no body hair, and have powder-white skin. While they need a little meat (about a pound) and water (eight ounces) each week to keep their bodies at peak ability, the vast majority of a Psi-Stalker’s nourishment comes from draining arcane and psionic energy from other entities. The average person usually has too little, so the preferred source is either inherently powered (such as Xiticix or demons) or those with an Arcane Background. Most Psi-Stalkers prefer to kill the source, but they are smart enough to know it’s not always a good idea. Some scientists and scholars believe Psi-Stalkers represent the world’s ecosystem creating a natural predator for the vast number of supernatural threats roaming the planet. The typical Psi-Stalker remains with her tribe for life, pursuing the tribe’s enemies and prey. Individual Psi-Stalkers chart their own course. Many serve the Coalition, which values their outdoor skills and talents for hunting the supernatural and psionically powerful. Others yearn to know more of the world than what the tribe explores."),
	QUICK_FLEX("Like the Grackle Tooth, most people have no idea where Quick-Flex Aliens come from. Some of them have mentioned they were originally known as the Quindorra, a name apparently handed down through their bloodlines. Most are unsure and don’t care; Earth is their home now. Casual observers would assume a Quick-Flex is human, as they have the same body, hair, skin color, and general appearance. Those who look closer notice their larger eyes, bare slits for a nose, and slightly longer faces. Quick-Flex are certainly different enough to fall under the Coalition’s ban on D-Bees. They also tend to be a few inches shorter, on average, than humans. As the colloquial name implies, these beings are incredibly agile and fast. They have a natural affinity for athletics, acrobatics, and physical activities where grace, dexterity, and nimbleness are needed. Plenty of Quick-Flex Aliens make their living as gunslinging mercenaries, hot-shot drivers, and daredevil pilots."),
	SIMVAN("Ranging from five-and-a-half to six feet tall, Simvan have wide jaws, pointed ears slightly larger than a human’s, and a mane of long, thick hair. Their nose and mouth extend into a short muzzle, and they are covered in short fur. The nomadic Simvan typically have trim, muscular bodies. The “Monster Riders” have a violent reputation among the world’s inhabitants. most consider the Simvan barbaric at best, cannibals who believe eating enemies (and their own fallen warriors) is a high honor. Despite their notoriety, Simvan are perfectly capable of trade and general social interaction, and many individuals develop an interest in learning more about the world outside their tribes. Their affinity for mounts considered by most to be terrifying monsters make the Simvan powerful foes and valued allies. Although capable of taming almost any animal, a Simvan is often found riding a Fury Beetle, Rhino-Buffalo, or Ostrosaurus (see Savage Foes of North America)."),
	TRIMADORE("Trimadore stand seven to eight feet tall with long, thick necks tapering off to comparatively small heads. They have almond-shaped eyes, thin, nearly lipless mouths, and miniscule, rounded ears. Legs and arms are thin and long and of equal length. The feet have two large toes while the hands have two thick fingers and a thumb. In other words, Trimadore are very alien in appearance to most humans. The species has an extraordinary knack for all things mechanical and technological. They also tend to be very gentle by nature, though remarkable individuals of the race find themselves drawn to grand adventures. Unsurprisingly, many Trimadore find the life of an Operator or a Techno-Wizard to their liking, and they’re exceedingly good at those fields. While Trimadore suffer the same difficulties as many other D-Bees who have non-standard physiologies, their mechanical aptitudes often help to offset those penalties. Most Trimadore wear armor of their own customization, and if given half a chance, modify vehicles to allow for their easier operation.");

	private String description;
	public String getDescription() {
		return description;
	}
	RaceType(String description) {
		this.description = description;
	}
}