USE savage_rifts;

CREATE TABLE `framework_feature` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`framework` BIGINT(20) NOT NULL,
	`framework_feature_type` VARCHAR(255) NOT NULL,
	`framework_ability_type` VARCHAR(255) NOT NULL,
	`provided_edge` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	INDEX `FK_framework_feature__framework` (`framework`),
	INDEX `FK_framework_feature__edge` (`provided_edge`),
	CONSTRAINT `FK_framework_feature__framework` FOREIGN KEY (`framework`) REFERENCES `framework` (`id`),
	CONSTRAINT `FK_framework_feature__edge` FOREIGN KEY (`provided_edge`) REFERENCES `edge` (`id`)
) COLLATE='utf8_general_ci' ENGINE=InnoDB;

SELECT @COMBAT_CYBORG_ID:=id FROM framwork WHERE type = 'COMBAT_CYBORG';

INSERT INTO `framework_feature` (`framework`, `framework_feature_type`, `framework_ability_type`) VALUES 
(@COMBAT_CYBORG_ID, 'BIONIC_AUGMENTATION', 'BONUS'),
(@COMBAT_CYBORG_ID, 'CYBERNETIC_ENHANCEMENTS', 'BONUS'),
(@COMBAT_CYBORG_ID, 'HIGH_PERFORMANCE_LEGS', 'BONUS'),
(@COMBAT_CYBORG_ID, 'MDC_ARMOR', 'BONUS'),
(@COMBAT_CYBORG_ID, 'MORE_MACHINE', 'BONUS'),
(@COMBAT_CYBORG_ID, 'SIZE', 'BONUS'),
(@COMBAT_CYBORG_ID, 'UPGRADABLE', 'BONUS'),
(@COMBAT_CYBORG_ID, 'UNARMED_COMBAT', 'BONUS'),

(@COMBAT_CYBORG_ID, 'ALL_THOSE_MOVING_PARTS', 'COMPLICATION'),
(@COMBAT_CYBORG_ID, 'GRAY_MATTER', 'COMPLICATION'),
(@COMBAT_CYBORG_ID, 'HEAVY', 'COMPLICATION'),
(@COMBAT_CYBORG_ID, 'INHUMAN_APPEARANCE', 'COMPLICATION'),
(@COMBAT_CYBORG_ID, 'LOSS_OF_DEXTERITY', 'COMPLICATION'),
(@COMBAT_CYBORG_ID, 'MALFUNCTION', 'COMPLICATION'),
(@COMBAT_CYBORG_ID, 'SHADOW_OF_THEMSELVES', 'COMPLICATION'),
(@COMBAT_CYBORG_ID, 'SPIRITUALLY_NUMB', 'COMPLICATION'),
(@COMBAT_CYBORG_ID, 'TOTAL_CONVERSION', 'COMPLICATION'),

(@COMBAT_CYBORG_ID, 'BIO_REGENERATION', 'BONUS'),
(@COMBAT_CYBORG_ID, 'ENHANCED_ATTRIBUTES', 'BONUS'),
(@COMBAT_CYBORG_ID, 'ENHANCED_SPEED', 'BONUS'),
(@COMBAT_CYBORG_ID, 'HEIGHTENED_SENSES', 'BONUS'),
(@COMBAT_CYBORG_ID, 'MINOR_PSIONIC', 'BONUS'),
(@COMBAT_CYBORG_ID, 'QUICK', 'BONUS'),
(@COMBAT_CYBORG_ID, 'SUPER_ENDURANCE', 'BONUS'),
(@COMBAT_CYBORG_ID, 'SUPER_REFLEXES', 'BONUS'),

(@COMBAT_CYBORG_ID, 'CYBERNETICS', 'COMPLICATION'),
(@COMBAT_CYBORG_ID, 'DISTINCTIVE_APPEARANCE', 'COMPLICATION'),
(@COMBAT_CYBORG_ID, 'MAGIC', 'COMPLICATION'),
(@COMBAT_CYBORG_ID, 'NEEDS_ACTION', 'COMPLICATION'),
(@COMBAT_CYBORG_ID, 'UNSTABLE_PSYCHO', 'COMPLICATION');


INSERT INTO `sql_files` (`sql_file_name`, `run_date`) VALUES ('13.sql', NOW());