CREATE TABLE `sheet` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`agility_bonus` INT(11) NULL DEFAULT NULL,
	`agility_die_type` VARCHAR(255) NULL DEFAULT NULL,
	`charisma` INT(11) NULL DEFAULT NULL,
	`has_completed_table_rolls` BIT(1) NULL DEFAULT NULL,
	`has_selected_edges` BIT(1) NULL DEFAULT NULL,
	`has_selected_hindrances` BIT(1) NULL DEFAULT NULL,
	`isp` INT(11) NULL DEFAULT NULL,
	`pace` INT(11) NULL DEFAULT NULL,
	`parry` INT(11) NULL DEFAULT NULL,
	`ppe` INT(11) NULL DEFAULT NULL,
	`remaining_attribute_points` INT(11) NULL DEFAULT NULL,
	`remaining_hindrance_points` INT(11) NULL DEFAULT NULL,
	`remaining_skill_points` INT(11) NULL DEFAULT NULL,
	`smarts_bonus` INT(11) NULL DEFAULT NULL,
	`smarts_die_type` VARCHAR(255) NULL DEFAULT NULL,
	`spirit_bonus` INT(11) NULL DEFAULT NULL,
	`spirit_die_type` VARCHAR(255) NULL DEFAULT NULL,
	`strain` INT(11) NULL DEFAULT NULL,
	`strength_bonus` INT(11) NULL DEFAULT NULL,
	`strength_die_type` VARCHAR(255) NULL DEFAULT NULL,
	`toughness` INT(11) NULL DEFAULT NULL,
	`vigor_bonus` INT(11) NULL DEFAULT NULL,
	`vigor_die_type` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
) COLLATE='latin1_swedish_ci' ENGINE=InnoDB;
